# Generated by Django 2.0.5 on 2019-08-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('score', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('editors_choice', models.CharField(max_length=100)),
            ],
        ),
    ]
